services:
  - type: web
    name: nasa-apod
    runtime: java
    buildCommand: ./build.sh
    startCommand: java -jar target/nasa-apod-backend-1.0-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
      - key: NASA_API_KEY
        value: your_api_key_here